[project]
name = "clean-staging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.20"
dependencies = [
    "psycopg2==2.8.6",
    "sortedcontainers>=2.4.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
